### ISSUE TITLE
1주차 필수 요구사항

### ISSUE THREAD

**Issue by jdi022222** [likelion-backendschool/FinalProject_JangDongIk_team1#1]
## 이슈 내용
* 회원, 글 작성 관련 내용

### **회원**

- 회원은 일반회원과 작가회원이 있다.
- 가입 직후는 일반회원이고, 작가명 등록을 하면 작가회원이 된다.
- 작가회원이 되면 상품(책)을 등록할 수 있다.
- 별개로 authLevel 의 값이 7이면 관리자의 역할도 수행할 수 있다.
- 회원가입
    - 회원가입시 축하메일을 발송한다.
- 로그인
    - 스프링 시큐리티를 사용하여 구현한다.
- 로그아웃
    - 스프링 시큐리티를 사용하여 구현한다.
- 프로필
    - 작가명을 입력하고, 작가 회원이 될 수 있다.
- 비밀번호변경
- 아이디 찾기
    - 가입 시 입력한 이메일 주소를 입력하여 아이디를 찾을 수 있다.
- 비밀번호 찾기
    - 로그인 시 필요한 아이디와 이메일로 비밀번호를 찾을 수 있다.
    - 이메일로 임시 비밀번호를 발송한다.
    
### **글 관리기능**

- 글 작성/수정
    - 마크다운 원문과 렌더링 결과(HTML)까지 같이 저장한다.
- 글 리스트
    - 제목과 글의 해시태그들을 볼 수 있다.
    - 해시태그를 클릭하면 내가 작성한 글 중 해당 해시태그와 관련된 글들을 볼 수 있다.
- 글 삭제
    - 글이 삭제되면 글 리스트로 리다이렉트 한다.
    - 삭제버튼 눌렀을 때 confirm 창으로 삭제여부를 한 번 더 물어본다.
- 글 상세화면
    - 글의 제목, 내용, 해시태그를 모두 출력
    - 글의 내용은 마크다운 해석이 되어야 한다.

### **ERD**
![image](https://user-images.githubusercontent.com/97517890/196475224-402bba47-b2fd-4842-8d10-f736dadbdd5e.png)

## 체크리스트
- [x] #2
- [x] #9
- [x] #4
- [x] #6
- [x] #7
- [x] #11
- [x] #13
- [x] #10
- [x] #12

**Comment by CocoIsCat** [comment]
끼요오오옷
